### ISSUE TITLE
do you have an example ?

### ISSUE THREAD

**Issue by annrapid** [jereinhardt/prospero#1]
Hi there,
I wanted to know if you have an example for prospero?

**Comment by arduino-man** [comment]
Hi there, I would love an example as well. Is this project  dead? Also, please consider adding the project to Hex PM. Thanks!

**Comment by jereinhardt** [comment]
Sorry to be so late to respond to this.  In terms of an example, I do use this in another open source project of mine called job bot https://github.com/jereinhardt/job_bot_app.  It is used in the new job search view.  Take a look at that, and if you still have questions, maybe I will whip up an example app to add here.

As far is if this project is dead, when I finished the initial version, I didn't really have an idea of where to go with it, and moved on to other projects.  So, while there is no roadmap for planned updates, I'm happy to discuss ideas for updates and features, and I'd be happy to review pull requests as well.

**Comment by arduino-man** [comment]
Thank you for responding. I've moved on as well but will consider looking through the project files and seeing how I can potentially improve things. I think this issue can be closed. Again, thanks.
